name: flutter_bloc_blog
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  floor: any
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_snake_navigationbar: ^0.6.1
  get_it: ^8.0.2
  mockito: ^5.4.4
  retrofit: ^4.4.1
dev_dependencies:
  build_runner: ^2.4.13
  floor_generator: ^1.5.0

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
